const EVENT_PREFIX = "pre";
const EVENT_POSTFIX = "post";
const STRING_BOOLEAN = "boolean";
const STRING_FUNCTION = "function";
const STRING_NUMBER = "number";
const STRING_OBJECT = "object";
const STRING_STRING = "string";
const STRING_UNDEFINED = "undefined";
const EVENT_CONFIGURE = "Configure";
const EVENT_PRE_CONFIGURE = EVENT_PREFIX + EVENT_CONFIGURE;
const EVENT_POST_CONFIGURE = EVENT_POSTFIX + EVENT_CONFIGURE;

export {
    STRING_BOOLEAN,
    STRING_FUNCTION,
    STRING_NUMBER,
    STRING_OBJECT,
    STRING_STRING,
    STRING_UNDEFINED,
    EVENT_PRE_CONFIGURE,
    EVENT_POST_CONFIGURE,
};
